Check for parameters in decrypt script  Decrypt script cleanup

diff --git a/decrypt b/decrypt
--- a/decrypt
+++ b/decrypt
@@ -1,5 +1,14 @@
 #!/bin/bash
 
+EXPECTED_ARGS=1
+E_BADARGS=65
+
+if [ $# -ne $EXPECTED_ARGS ]
+then
+  echo "Usage: `basename $0` FILE"
+  exit $E_BADARGS
+fi
+
 enc_filename=$1
 dec_filename=`echo $enc_filename | sed 's/\./ /g' | awk '{print $1"."$2}'`
 final_filename=`echo $enc_filename | sed 's/\./ /g' | awk '{print $1}'`
@@ -10,8 +19,10 @@ RESULT=$?
 
 rm $dec_filename
 
-if [ $RESULT -ne 0 ]; then
-    echo "Error encrypting";exit 1;
+if [ $RESULT -ne 0 ]
+then
+    echo "Error encrypting"
+    exit 1
 fi
 rm -rf $enc_filename
 
